version: '2'

services:    
  mysql-service: 
    image: mysql:5.6
    container_name: mysql_con
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_jprsc
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - default
    ports:
      - 3302:3306

  website:
    build: ./app
    container_name: php_web    
    volumes:
      - ./app:/var/www/html
    networks:
      - default
    ports:
      - 8010:80
    depends_on:
      - mysql-service
